import Vue from 'vue';
import { ValidationProvider, ValidationObserver } from 'vee-validate';
import LayoutsContainerLgComponent from './layouts/LayoutsContainerLgComponent';
import RightSideBarComponent from './right-side-bar/RightSideBarComponent';
import FooterButtonsComponent from './right-side-bar/FooterButtonsComponent';
import TextInputComponent from './form-elements/TextInputComponent';
import TextInfoComponent from './form-elements/TextInfoComponent';
import TelInputComponent from './form-elements/TelInputComponent';
import TextareaComponent from './form-elements/TextareaComponent';
import RadioInputComponent from './form-elements/RadioInputComponent';
import CurrencyInputComponent from './form-elements/CurrencyInputComponent';
import DatepickerComponent from './form-elements/DatepickerComponent';
import SelectComponent from './form-elements/SelectComponent';
import ActionButton from './form-elements/ActionButton';
import AmountInfoComponent from './AmountInfoComponent';
import FilterComponent from './left-side-bar/FilterComponent';
import TypeFilterComponent from './left-side-bar/TypeFilterComponent';
import CategoryTypeFilterComponent from './left-side-bar/CategoryTypeFilterComponent';
import MethodFilterComponent from './left-side-bar/MethodFilterComponent';
import ContactFilterComponent from './left-side-bar/ContactFilterComponent';
import RangeFilterComponent from './left-side-bar/RangeFilterComponent';
import NotesFilterComponent from './left-side-bar/NotesFilterComponent';
import InactiveFilterComponent from './left-side-bar/InactiveFilterComponent';
import LeftSideBarComponent from './left-side-bar/LeftSideBarComponent';
import InactiveBadgeComponent from './InactiveBadgeComponent';
import FileUploadComponent from './FileUploadComponent';
import LoaderComponent from './LoaderComponent';

Vue.component('ValidationProvider', ValidationProvider);
Vue.component('ValidationObserver', ValidationObserver);
Vue.component('LayoutsContainerLgComponent', LayoutsContainerLgComponent);
Vue.component('RightSideBarComponent', RightSideBarComponent);
Vue.component('FooterButtonsComponent', FooterButtonsComponent);
Vue.component('TextInputComponent', TextInputComponent);
Vue.component('TextInfoComponent', TextInfoComponent);
Vue.component('TextareaComponent', TextareaComponent);
Vue.component('TelInputComponent', TelInputComponent);
Vue.component('RadioInputComponent', RadioInputComponent);
Vue.component('CurrencyInputComponent', CurrencyInputComponent);
Vue.component('DatepickerComponent', DatepickerComponent);
Vue.component('SelectComponent', SelectComponent);
Vue.component('ActionButton', ActionButton);
Vue.component('AmountInfoComponent', AmountInfoComponent);
Vue.component('FilterComponent', FilterComponent);
Vue.component('TypeFilterComponent', TypeFilterComponent);
Vue.component('CategoryTypeFilterComponent', CategoryTypeFilterComponent);
Vue.component('MethodFilterComponent', MethodFilterComponent);
Vue.component('ContactFilterComponent', ContactFilterComponent);
Vue.component('RangeFilterComponent', RangeFilterComponent);
Vue.component('NotesFilterComponent', NotesFilterComponent);
Vue.component('InactiveFilterComponent', InactiveFilterComponent);
Vue.component('LeftSideBarComponent', LeftSideBarComponent);
Vue.component('InactiveBadgeComponent', InactiveBadgeComponent);
Vue.component('FileUploadComponent', FileUploadComponent);
Vue.component('LoaderComponent', LoaderComponent);
